spring.application.name=UC17
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/nakul
spring.datasource.username=root
spring.datasource.password=Nakul@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
